# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mantenedor_productos_pb2 as mantenedor__productos__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mantenedor_productos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductMaintainerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProduct = channel.unary_unary(
                '/mantenedor_productos.ProductMaintainer/GetProduct',
                request_serializer=mantenedor__productos__pb2.GetProductRequest.SerializeToString,
                response_deserializer=mantenedor__productos__pb2.Product.FromString,
                _registered_method=True)
        self.CreateProduct = channel.unary_unary(
                '/mantenedor_productos.ProductMaintainer/CreateProduct',
                request_serializer=mantenedor__productos__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=mantenedor__productos__pb2.Product.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/mantenedor_productos.ProductMaintainer/UpdateProduct',
                request_serializer=mantenedor__productos__pb2.UpdateProductRequest.SerializeToString,
                response_deserializer=mantenedor__productos__pb2.Product.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/mantenedor_productos.ProductMaintainer/DeleteProduct',
                request_serializer=mantenedor__productos__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=mantenedor__productos__pb2.DeleteProductResponse.FromString,
                _registered_method=True)
        self.UploadProductImage = channel.stream_unary(
                '/mantenedor_productos.ProductMaintainer/UploadProductImage',
                request_serializer=mantenedor__productos__pb2.UploadProductImageRequest.SerializeToString,
                response_deserializer=mantenedor__productos__pb2.UploadProductImageResponse.FromString,
                _registered_method=True)
        self.GetAllProducts = channel.unary_unary(
                '/mantenedor_productos.ProductMaintainer/GetAllProducts',
                request_serializer=mantenedor__productos__pb2.GetAllProductsRequest.SerializeToString,
                response_deserializer=mantenedor__productos__pb2.ProductList.FromString,
                _registered_method=True)


class ProductMaintainerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadProductImage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllProducts(self, request, context):
        """Nuevo método para obtener todos los productos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductMaintainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=mantenedor__productos__pb2.GetProductRequest.FromString,
                    response_serializer=mantenedor__productos__pb2.Product.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=mantenedor__productos__pb2.CreateProductRequest.FromString,
                    response_serializer=mantenedor__productos__pb2.Product.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=mantenedor__productos__pb2.UpdateProductRequest.FromString,
                    response_serializer=mantenedor__productos__pb2.Product.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=mantenedor__productos__pb2.DeleteProductRequest.FromString,
                    response_serializer=mantenedor__productos__pb2.DeleteProductResponse.SerializeToString,
            ),
            'UploadProductImage': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadProductImage,
                    request_deserializer=mantenedor__productos__pb2.UploadProductImageRequest.FromString,
                    response_serializer=mantenedor__productos__pb2.UploadProductImageResponse.SerializeToString,
            ),
            'GetAllProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllProducts,
                    request_deserializer=mantenedor__productos__pb2.GetAllProductsRequest.FromString,
                    response_serializer=mantenedor__productos__pb2.ProductList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mantenedor_productos.ProductMaintainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mantenedor_productos.ProductMaintainer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductMaintainer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mantenedor_productos.ProductMaintainer/GetProduct',
            mantenedor__productos__pb2.GetProductRequest.SerializeToString,
            mantenedor__productos__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mantenedor_productos.ProductMaintainer/CreateProduct',
            mantenedor__productos__pb2.CreateProductRequest.SerializeToString,
            mantenedor__productos__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mantenedor_productos.ProductMaintainer/UpdateProduct',
            mantenedor__productos__pb2.UpdateProductRequest.SerializeToString,
            mantenedor__productos__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mantenedor_productos.ProductMaintainer/DeleteProduct',
            mantenedor__productos__pb2.DeleteProductRequest.SerializeToString,
            mantenedor__productos__pb2.DeleteProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadProductImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/mantenedor_productos.ProductMaintainer/UploadProductImage',
            mantenedor__productos__pb2.UploadProductImageRequest.SerializeToString,
            mantenedor__productos__pb2.UploadProductImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mantenedor_productos.ProductMaintainer/GetAllProducts',
            mantenedor__productos__pb2.GetAllProductsRequest.SerializeToString,
            mantenedor__productos__pb2.ProductList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
